<a href="https://colab.research.google.com/github/Dewmi-2003/Dewmi-2003/blob/main/ML_Practical_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd

In [71]:
from sklearn.linear_model import LinearRegression

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
model=LinearRegression()

In [74]:
df=pd.read_csv("/content/Student_Performance.csv")

In [75]:
df.shape

(10000, 6)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [77]:
X=df[["Hours Studied","Previous Scores","Extracurricular Activities","Sleep Hours","Sample Question Papers Practiced"]]
y=df["Performance Index"]

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [79]:
df["year"]=2026 #add new column

In [80]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,year
0,7,99,Yes,9,1,91.0,2026
1,4,82,No,4,2,65.0,2026
2,8,51,Yes,7,2,45.0,2026
3,5,52,Yes,5,2,36.0,2026
4,7,75,No,8,5,66.0,2026

In [81]:
df.drop("year",axis=1) #Remove column

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [82]:
df.drop(1) #Remove row

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,year
0,7,99,Yes,9,1,91.0,2026
2,8,51,Yes,7,2,45.0,2026
3,5,52,Yes,5,2,36.0,2026
4,7,75,No,8,5,66.0,2026
5,3,78,No,9,6,61.0,2026
...,...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0,2026
9996,7,64,Yes,8,5,58.0,2026
9997,6,83,Yes,8,5,74.0,2026
9998,9,97,Yes,7,0,95.0,2026
9999,7,74,No,8,1,64.0,2026

In [83]:
df.sort_values("Sleep Hours") #Sorting Data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,year
7,8,45,Yes,4,6,42.0,2026
6603,2,56,No,4,0,30.0,2026
9941,3,56,Yes,4,5,36.0,2026
9938,6,64,Yes,4,9,48.0,2026
9937,8,59,Yes,4,7,54.0,2026
...,...,...,...,...,...,...,...
8125,9,94,No,9,5,89.0,2026
3587,6,80,Yes,9,5,73.0,2026
3588,3,98,No,9,0,80.0,2026
3601,9,85,Yes,9,6,85.0,2026
3604,1,48,Yes,9,1,25.0,2026

In [84]:
df.sort_values("Hours Studied", ascending=False) #Descending

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,year
2222,9,62,Yes,7,5,56.0,2026
9987,9,74,No,4,6,69.0,2026
9955,9,88,No,8,2,84.0,2026
9977,9,84,No,6,6,82.0,2026
9990,9,43,No,7,4,40.0,2026
...,...,...,...,...,...,...,...
5565,1,46,Yes,5,0,17.0,2026
5562,1,43,Yes,9,8,20.0,2026
5561,1,83,No,5,3,59.0,2026
5560,1,80,No,6,3,55.0,2026
5558,1,91,No,6,0,61.0,2026

In [85]:
df.groupby("Previous Scores") #Group By

In [86]:
print(df)

      Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9
1                 4               82                         No            4
2                 8               51                        Yes            7
3                 5               52                        Yes            5
4                 7               75                         No            8
...             ...              ...                        ...          ...
9995              1               49                        Yes            4
9996              7               64                        Yes            8
9997              6               83                        Yes            8
9998              9               97                        Yes            7
9999              7               74                         No            8

      Sample Question Papers Practiced  Performance Index  year
0                                    1               91.0  2026
1                                    2               65.0  2026
2                                    2               45.0  2026
3                                    2               36.0  2026
4                                    5               66.0  2026
...                                ...                ...   ...
9995                                 2               23.0  2026
9996                                 5               58.0  2026
9997                                 5               74.0  2026
9998                                 0               95.0  2026
9999                                 1               64.0  2026

[10000 rows x 7 columns]

In [87]:
df.to_csv("output.csv", index=False) #Save to CSV

In [88]:
df.to_excel("output.xlsx", index=False) #Save to Excel

In [89]:
df.isnull().sum() #Check for null (missing) values

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
year                                0
dtype: int64

In [90]:
df["Sleep Hours"].fillna(df["Sleep Hours"].mean())

0       9
1       4
2       7
3       5
4       8
       ..
9995    4
9996    8
9997    8
9998    7
9999    8
Name: Sleep Hours, Length: 10000, dtype: int64